src/client.rs
src/lib.rs
src/response.rs
tests/client.rs
tests/request.rs

This PR changes the current behavior of the Response type.
Previously the body was consumed when reading the response. This is now split in two so that only the headers are read to create the Response type. The user can then later read the response body.
TODO: How to handle if the user does not actually read the body? We should probably drain the connection in this case on Drop or something similar.

Let response only read headers and defer reading body

---

src/client.rs
src/lib.rs
src/request.rs
src/response.rs
tests/client.rs
tests/request.rs

This is a proposal for an easier to use api that propagates the underlying connection from when it is established using `HttpClient::endpoint()`.
It removes the ability to do:
```rust
let (response, mut conn) = HttpClient::request(Method::GET, "http://google.dk").await.unwrap().send(&mut rx_buf).await.unwrap();
response.body(&mut conn).read_to_end().await
```
which should now instead be
```rust
let mut endpoint = HttpClient::endpoint("http://google.dk").await;
endpoint.get("/").send(&mut rx_buf).await.unwrap().body().read_to_end().await
```
@lulf  Let me know what you think.

Add HttpEndpoint

---

src/response.rs
tests/client.rs
tests/request.rs

This is now possible because we support all possible response types

Make accessing response body infallible

---

src/response.rs

Add missing `?` for the `map_err()` in `keep-alive` in the response, according to https://github.com/drogue-iot/reqwless/pull/36#issuecomment-1589203952

Fix error for keep-alive header

---

Cargo.toml
src/client.rs
src/concat.rs
src/lib.rs
src/request.rs
src/response.rs
tests/client.rs
tests/request.rs

I realize there is already discussion and plans to address this in #39 but I had the urge to update my hobby embassy project _now_: ;)
I'm still posting it, in case someone finds it useful
I mostly propagate WriteAllError or collapse it down to `embedded_io::ErrorKind` when that's not an option.

(hacky) update embedded-io to 0.5

---

src/client.rs

There's a `From<>` impl that is automatically called by the question mark operator. This wasn't the only change I meant to do with errors, but... baby steps

Remove explicit error conversion

---

src/response.rs

If we read a newline in place of the chunk length, `total_read` is 0 and the subtraction for the `\r` check underflows. This PR fixes this issue.

Don't panic if chunked encoding contains no chunk length

---

CHANGELOG.md
src/response.rs

This fixes a regression introduced with `BufRead` support.
This replaces the commits I made to #57.

Ensure that the final chunk end termination is read

---

Cargo.toml

Unfortunately we currently have `heapless::Vec` exposed in https://github.com/drogue-iot/reqwless/blob/main/src/response.rs#L27.

Update heapless dependency

---

src/lib.rs
src/reader.rs
src/response.rs
src/response/chunked.rs
src/response/fixed_length.rs
src/response/mod.rs
tests/client.rs
tests/connection.rs
tests/request.rs

I had to do a bunch of refactoring, because I had to create an abstraction for `maybe-BufRead` types (and I had to implement that for the tokio adapter stuff). This is because ChunkedEncoding's new reader function works via BufRead.
A downside of this PR is that `read_to_end` is only available for `TryBufRead` types, which we only define for `HttpConnection` in the library, and the tokio adapter in the tests.
The PR can most likely be simplified, I was just aiming to get it working and it took long enough.

Allow read_to_end with ChunkedEncoding

---

Cargo.toml
rust-toolchain.toml
src/lib.rs
tests/client.rs

Fixes #63
Requires https://github.com/rmja/buffered-io/pull/6

feat: update to use stable rust

---

Cargo.toml
README.md
src/client.rs
src/lib.rs

CC #49 
This is based off embedded_tls support. It provides an alternative to use `mbedtls` for the `esp32`, which has its own lot of features and optimizations, like hardware acceleration and client certificate verification.

feat(esp-mbedtls): Add initial support for using esp-mbedtls in the client instead of embedded_tls

---

src/response/mod.rs

The `Status` enum only supports a portion of the response codes defined by [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-status-codes).  If the server returned a response code other than one of the ones supported by the `Status` enum, the code previously threw away the value.  This updates the code to also store the code as an integer, so that users can handle other values.
I considered simply changing the `Unknown` variant to use `Unknown(u16)`, but avoided it for now since this would break backwards compatibility, and would also prevent using `status as u16` to convert `Status` values to integers.

Support accessing the response code as an integer

---

src/response/mod.rs

This makes more sense now where `StatusCode` is the exposed api

Move the Status helpers to StatusCode

---

src/response/chunked.rs
tests/client.rs

`fill_buf()` will not return until there is at least one byte available to read. This will not happen when the entire chunked body is read.
cc @bugadani

Fix bug when calling fill_buf() when there are no remaining bytes

---

src/body_writer.rs

This fixes an issue in `BufferingChunkedBodyWriter` where if the prewritten data is so large that it almost matches the buffer capacity in such a way that the writer is unable to have any chunks in the buffer, then it will write the prewritten bytes to the underlying connection to make room for the first chunk.

Make an effort to ensure that write() does not return Ok(0)

---

src/body_writer/buffering_chunked.rs
src/body_writer/chunked.rs
src/body_writer/fixed.rs
src/body_writer/mod.rs
src/client.rs

Split body_writer into its constituent parts

---

CHANGELOG.md
src/body_writer/buffering_chunked.rs

This fixes an issue where a call to write() with a buffer length exactly matching the remaining size of the remainder of the current chunk causes the entire chunk to be discarded. Depends on #84 .

Fix exact write

---

src/client.rs
src/lib.rs

esp-mbedtls now expects to be passed a mutable reference to the raw peripheral, instead of to the peripheral container.

Fix esp-mbedtls support after bump to esp-hal 0.18

---

src/client.rs

This fixes compatibility issues with the latest breaking changes in `esp-mbedtls`.
/cc @GnomedDev You might want to test this, since you've been using the library.

Fix esp-mbedtls support after esp-rs/esp-mbedtls@7de5d0a

---

src/request.rs

This enables looping over the same request call for retries.

Allow `request::Method` to be copied and cloned

---

src/response/mod.rs

Hi, this PR simply rexportes the `ChunkedBodyReader` and `FixedLengthBodyReader` structs. There is currently a warning from clippy about the `Try` trait, but that's unrelated to this PR.

Reexported response readers.

---

src/headers.rs

Thanks for the work on this crate!
This adds support for the [`text/html` `Content-Type`](https://www.iana.org/assignments/media-types/text/html), which otherwise defaults to `application/octet-stream`. I understand that this may be less relevant than e.g.`application/json` in an embedded context, but I believe it's still useful to have.

feat(headers): add support for the `text/html` `Content-Type`

---

src/client.rs
src/lib.rs

This updates the compatibility with the latest HEAD of `esp-mbedtls`, after https://github.com/esp-rs/esp-mbedtls/commit/1431835a9a3464820e97203347ec33e313f8e116

fix: Update esp-mbedtls compatiblity with latest HEAD

---

Cargo.toml

Update the `nourl` crate to version `0.1.2`. Fixes #111

Update nourl to version 0.1.2

---

Cargo.toml

Fixes issue [#108](https://github.com/drogue-iot/reqwless/issues/108)

The defmt feature should enable defmt in heapless (Fixes issue #108)
